### ISSUE TITLE
PIT distribution

### ISSUE THREAD

**Issue by colineCJ** [bmtglobal/epower#9]
Hello,
I have a new question:
I am not very familiar with Bayesian statistics.
Why do we want a flat distribution of PIT, and what does it mean if not flat ? Is it related to model specification ? How can we improve it ? Thanks !
![image](https://user-images.githubusercontent.com/90379569/133128728-f77970fc-3bef-4766-842b-896e8530e1ec.png)

**Comment by beckyfisher** [comment]
Hi colineCJ, 
The PIT diagram gives an indication of how well the model is able to predict the observed data. If you want the technical details, a reference would be: REF: Marshall, E. C., and D. J. Spiegelhalter (2003). Approximate Cross-Validatory Predictive Checks in Disease Mapping Models. Statistics in Medicine 22, 1649-60.
But in simple terms, if the model was fitted to the data with yi removed, the PIT is the probability that a new yi would be less than the actual yi.  If the model represents the data well, the PIT values should have an approximate uniform distribution. SO a skewed distribution as you present above is a clear indicator that the model doesn't fit the data well. In simulation based power analysis this is a bit of a problem, because the fitted model is being used to build the simulations, so your results might be completely wrong for real data. . The only way to improve the model (within epower) would be to try altering the hierarchical structure of the model (maybe there is a grouping variable that is not accounted for?) or change the distribution being used for modelling (but if you are already using the right theoretical distribution this is not possible). More specific advice could only be given with a thorough understanding of your usage case, and is not something we can really provide within this forum. Other than those two suggestions there may be other ways to improve the model, like including covariates etc, but they are not currently supported by epower unfortunately.

**Comment by colineCJ** [comment]
Thanks, that is very useful !! I was surprised to not see such a reference or description of model validation in the appendix, since it mentions that this step is crucial. Thank you very much for the reference.
